name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow-db"
database_id = "d06a481b-bb9d-412b-829d-d38d5af6bd73"
